import test from 'node:test'; import assert from 'node:assert/strict';
import { signProof } from '../src/haloproof/signer.js'; import { HaloProofKeys } from '../src/haloproof/keys.js';
import { HaloDelegation } from '../src/delegation/haloDelegation.js'; import { HaloRegistry } from '../src/registry/haloRegistry.js'; import { ReplayGuard } from '../src/haloproof/replayGuard.js'; import { HaloAudit } from '../src/audit/haloAudit.js'; import { RevocationRegistry } from '../src/haloproof/revocation.js'; import { processAgentRequest } from '../src/runtime/haloRuntime.js';

test('HaloProof basic checks',()=>{ const payload={type:'ConsentReceipt',x:1}; const proof=signProof(payload,HaloProofKeys.halo); assert.ok(typeof proof.signature==='string'); const g=HaloDelegation.grant({subject:'user-001',audience:'svc.health.verified-care',purpose:'find_nearest_care',scope:['share:approximate_location'],taskId:'task-1',consentReceiptId:'r'}); assert.ok(typeof HaloDelegation.verify({grantId:g.grant_id}).valid==='boolean'); });

test('delegation restrictions and replay',()=>{ const g=HaloDelegation.grant({subject:'user-001',audience:'svc.health.verified-care',purpose:'find_nearest_care',scope:['share:approximate_location'],taskId:'task-1',consentReceiptId:'r'}); HaloDelegation.get(g.grant_id).expires_at=new Date(Date.now()-1000).toISOString(); assert.equal(HaloDelegation.verify({grantId:g.grant_id}).valid,false); const g2=HaloDelegation.grant({subject:'user-001',audience:'svc.health.verified-care',purpose:'find_nearest_care',scope:['share:approximate_location'],taskId:'task-1',consentReceiptId:'r'}); RevocationRegistry.revoke({revocation_id:'revoke_1',target_id:g2.grant_id}); assert.equal(HaloDelegation.verify({grantId:g2.grant_id}).valid,false); assert.equal(ReplayGuard.checkAndUse('nonce-1'),true); assert.equal(ReplayGuard.checkAndUse('nonce-1'),false);});

test('registry and audit chain',()=>{ const s=HaloRegistry.get('svc.health.verified-care'); assert.ok(s.service_id==='svc.health.verified-care'); s.trust.status='revoked'; assert.equal(HaloRegistry.verify(s),false); s.trust.status='verified'; const out=processAgentRequest({userId:'user-001',prompt:'medical help',consentDecisions:{approximate_location:true,medical_history:false}}); assert.ok(out.status==='completed' || out.intent); assert.equal(HaloAudit.verifyChain('user-001'),true); });
