import express from 'express'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { HaloVault } from './vault/haloVault.js'; import { planIntent } from './runtime/intentPlanner.js'; import { HaloPolicy } from './policy/haloPolicy.js'; import { HaloConsent } from './consent/haloConsent.js'; import { HaloDelegation } from './delegation/haloDelegation.js'; import { HaloRegistry } from './registry/haloRegistry.js'; import { HaloResolver } from './resolver/haloResolver.js'; import { HaloConnect } from './connect/haloConnect.js'; import { HaloAudit } from './audit/haloAudit.js'; import { processAgentRequest } from './runtime/haloRuntime.js';
import { signProof } from './haloproof/signer.js'; import { verifyProof } from './haloproof/verifier.js'; import { HaloProofKeys } from './haloproof/keys.js'; import { RevocationRegistry } from './haloproof/revocation.js';
const app = express(); app.use(express.json()); const __filename = fileURLToPath(import.meta.url); const __dirname = path.dirname(__filename); app.use(express.static(path.join(__dirname, '..', 'public')));
app.get('/health', (_q, res) => res.json({ ok: true, product: 'AgentHalo' }));
app.post('/api/v1/proofs/sign',(q,r)=>r.json({proof:signProof(q.body.payload,HaloProofKeys.halo)}));
app.post('/api/v1/proofs/verify',(q,r)=>r.json({valid:verifyProof(q.body.payload,q.body.proof,HaloProofKeys.halo)}));
app.get('/api/v1/proofs/consent/:receiptId',(q,r)=>r.json(HaloConsent.get(q.query.consentId||'')?.receipt||{}));
app.get('/api/v1/proofs/delegation/:grantId',(q,r)=>r.json(HaloDelegation.get(q.params.grantId)||{}));
app.get('/api/v1/proofs/service/:serviceId',(q,r)=>r.json(HaloRegistry.get(q.params.serviceId)||{}));
app.get('/api/v1/proofs/revocation/:revocationId',(q,r)=>r.json(RevocationRegistry.get(q.params.revocationId)||{}));
app.post('/api/v1/delegations/:grantId/revoke',(q,r)=>{const g=HaloDelegation.revoke({grantId:q.params.grantId}); const rec={revocation_id:`revoke_${Date.now()}`,type:'RevocationRecord',target_type:'DelegationGrant',target_id:q.params.grantId,user_id:q.body.userId||'user-001',reason:'User revoked permission from Trust Inspector.',revoked_at:new Date().toISOString(),revoked_by:q.body.userId||'user-001'}; rec.proof=signProof(rec,HaloProofKeys.halo); RevocationRegistry.revoke(rec); r.json({grant:g,revocation:rec});});
app.post('/api/v1/delegations/:grantId/verify',(q,r)=>r.json(HaloDelegation.verify({grantId:q.params.grantId,audience:q.body.audience,action:q.body.action})));
app.get('/api/v1/trust-inspector/tasks/:taskId',(q,r)=>{const ev=HaloAudit.byTask('user-001',q.params.taskId); r.json({task_id:q.params.taskId,audit_chain:ev});});
app.get('/api/v1/trust-inspector/users/:userId',(q,r)=>r.json({user_id:q.params.userId,audit_chain:HaloAudit.byUser(q.params.userId)}));
app.get('/api/v1/audit/:userId/chain',(q,r)=>r.json(HaloAudit.byUser(q.params.userId)));
app.post('/api/v1/audit/:userId/verify-chain',(q,r)=>r.json({valid:HaloAudit.verifyChain(q.params.userId)}));
app.post('/api/v1/agent/request',(q,r)=>{try{r.json(processAgentRequest(q.body));}catch(e){r.status(400).json({error:e.message});}});
app.listen(process.env.PORT||3000,()=>console.log('AgentHalo running'));
